name: Daily Stock Report

on:
  schedule:
    # Runs at 10 PM UTC every day (adjust for your timezone / market close)
    - cron: "0 22 * * *"
  workflow_dispatch: # allows manual runs too

jobs:
  run-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance

    - name: Run daily report
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      run: |
        python email_ticker.py
